name = "Pipelines"
uuid = "b4c29205-8164-4dda-9f8d-e82e64627439"
authors = ["Geert Jan Bex <geertjan.bex@uhasselt.be>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
